"""
formalized_preferences_case_A.py
Generato automaticamente dal Workers Agent (Fase 1) il 2026-06-19T19:12:37.
Use Case A: preferenze formalizzate dei lavoratori.

Distinzione esplicita tra Vincoli Hard e Vincoli Soft:
  - HARD_CONSTRAINTS : vincoli inderogabili.
      'institutional' -> regole globali (max ore, turni mensili, ...);
      'per_worker'    -> per lavoratore: turni_vietati (divieti assoluti
                         sul tipo di turno) estratti dal linguaggio naturale.
  - SOFT_CONSTRAINTS : preferenze per lavoratore (turni_preferiti,
      turni_indesiderati, giorni_indesiderati = richieste di ferie,
      flexibility_score) e satisfaction_weights (modello di soddisfazione
      per la funzione obiettivo OR-Tools).
"""

HARD_CONSTRAINTS = {   'institutional': {   'max_ore_settimanali': 36,
                         'turni_mensili_esatti': 25,
                         'max_turni_per_giorno': 1,
                         'catena_turni_contigui_vietata': 'N->M',
                         'notte_turno_doppio': True,
                         'riposi_obbligatori_dopo_notte': 2,
                         'giorni_riposo_minimi': 1},
    'per_worker': {   'W01': {'nome': 'Marco Rossi', 'turni_vietati': []},
                      'W02': {'nome': 'Giulia Bianchi', 'turni_vietati': []},
                      'W03': {'nome': 'Luca Ferrari', 'turni_vietati': []},
                      'W04': {'nome': 'Sara Russo', 'turni_vietati': []},
                      'W05': {'nome': 'Andrea Esposito', 'turni_vietati': []},
                      'W06': {'nome': 'Chiara Romano', 'turni_vietati': []},
                      'W07': {'nome': 'Matteo Colombo', 'turni_vietati': []},
                      'W08': {'nome': 'Francesca Ricci', 'turni_vietati': ['N']},
                      'W09': {'nome': 'Davide Greco', 'turni_vietati': []},
                      'W10': {'nome': 'Elena Marino', 'turni_vietati': []},
                      'W11': {'nome': 'Alessandro Conti', 'turni_vietati': []},
                      'W12': {'nome': 'Valentina Bruno', 'turni_vietati': []},
                      'W13': {'nome': 'Simone Gallo', 'turni_vietati': []}}}

SOFT_CONSTRAINTS = {   'W01': {   'nome': 'Marco Rossi',
               'turni_preferiti': ['M'],
               'turni_indesiderati': ['N'],
               'giorni_indesiderati': ['2026-12-25'],
               'flexibility_score': 0.6,
               'satisfaction_weights': {'M': 5.0, 'P': 0.0, 'N': -2.4}},
    'W02': {   'nome': 'Giulia Bianchi',
               'turni_preferiti': ['M'],
               'turni_indesiderati': ['P'],
               'giorni_indesiderati': ['2026-12-24', '2026-12-25', '2026-12-26'],
               'flexibility_score': 0.2,
               'satisfaction_weights': {'M': 6.0, 'P': -4.8, 'N': 0.0}},
    'W03': {   'nome': 'Luca Ferrari',
               'turni_preferiti': ['N'],
               'turni_indesiderati': ['M'],
               'giorni_indesiderati': ['2027-01-01'],
               'flexibility_score': 0.4,
               'satisfaction_weights': {'M': -3.6, 'P': 0.0, 'N': 5.0}},
    'W04': {   'nome': 'Sara Russo',
               'turni_preferiti': ['P'],
               'turni_indesiderati': ['N'],
               'giorni_indesiderati': ['2026-12-31', '2027-01-01'],
               'flexibility_score': 0.1,
               'satisfaction_weights': {'M': 0.0, 'P': 5.0, 'N': -5.4}},
    'W05': {   'nome': 'Andrea Esposito',
               'turni_preferiti': ['P'],
               'turni_indesiderati': [],
               'giorni_indesiderati': [],
               'flexibility_score': 0.9,
               'satisfaction_weights': {'M': 0.0, 'P': 1.0, 'N': 0.0}},
    'W06': {   'nome': 'Chiara Romano',
               'turni_preferiti': ['M'],
               'turni_indesiderati': ['N'],
               'giorni_indesiderati': ['2026-12-08'],
               'flexibility_score': 0.2,
               'satisfaction_weights': {'M': 5.0, 'P': 0.0, 'N': -4.8}},
    'W07': {   'nome': 'Matteo Colombo',
               'turni_preferiti': ['N', 'P'],
               'turni_indesiderati': ['M'],
               'giorni_indesiderati': ['2026-12-19', '2026-12-20'],
               'flexibility_score': 0.3,
               'satisfaction_weights': {'M': -4.2, 'P': 4.0, 'N': 5.0}},
    'W08': {   'nome': 'Francesca Ricci',
               'turni_preferiti': ['M', 'P'],
               'turni_indesiderati': [],
               'giorni_indesiderati': ['2026-12-26'],
               'flexibility_score': 0.5,
               'satisfaction_weights': {'M': 5.0, 'P': 4.0, 'N': 0.0}},
    'W09': {   'nome': 'Davide Greco',
               'turni_preferiti': ['M', 'N'],
               'turni_indesiderati': ['P'],
               'giorni_indesiderati': ['2027-01-06'],
               'flexibility_score': 0.7,
               'satisfaction_weights': {'M': 3.0, 'P': -1.8, 'N': 3.0}},
    'W10': {   'nome': 'Elena Marino',
               'turni_preferiti': ['P', 'N'],
               'turni_indesiderati': ['M'],
               'giorni_indesiderati': ['2026-12-24', '2026-12-25', '2026-12-26'],
               'flexibility_score': 0.3,
               'satisfaction_weights': {'M': -4.2, 'P': 5.0, 'N': 4.0}},
    'W11': {   'nome': 'Alessandro Conti',
               'turni_preferiti': ['M'],
               'turni_indesiderati': ['N'],
               'giorni_indesiderati': ['2026-12-25'],
               'flexibility_score': 0.4,
               'satisfaction_weights': {'M': 5.0, 'P': 0.0, 'N': -3.6}},
    'W12': {   'nome': 'Valentina Bruno',
               'turni_preferiti': ['N'],
               'turni_indesiderati': [],
               'giorni_indesiderati': [],
               'flexibility_score': 0.9,
               'satisfaction_weights': {'M': 0.0, 'P': 0.0, 'N': 1.0}},
    'W13': {   'nome': 'Simone Gallo',
               'turni_preferiti': ['P', 'M'],
               'turni_indesiderati': ['N'],
               'giorni_indesiderati': ['2027-01-01', '2027-01-06'],
               'flexibility_score': 0.2,
               'satisfaction_weights': {'M': 4.0, 'P': 5.0, 'N': -4.8}}}

