"""
formalized_preferences_case_B.py
Generato automaticamente dal Workers Agent (Fase 1) il 2026-06-11T19:22:02.
Use Case B: preferenze formalizzate dei lavoratori.

Struttura per ogni lavoratore:
    turni_preferiti, turni_indesiderati, giorni_indisponibilita,
    flexibility_score (0-1) e satisfaction_weights (pesi per OR-Tools).
"""

WORKER_PREFERENCES = {   'W01': {   'nome': 'Marco Rossi',
               'turni_preferiti': ['M'],
               'turni_indesiderati': ['N'],
               'giorni_indisponibilita': ['2026-12-25'],
               'flexibility_score': 0.6,
               'satisfaction_weights': {'M': 1.0, 'P': 0.0, 'N': -0.5}},
    'W02': {   'nome': 'Giulia Bianchi',
               'turni_preferiti': ['M'],
               'turni_indesiderati': ['P'],
               'giorni_indisponibilita': ['2026-12-24', '2026-12-25', '2026-12-26'],
               'flexibility_score': 0.2,
               'satisfaction_weights': {'M': 1.0, 'P': -0.8, 'N': 0.0}},
    'W03': {   'nome': 'Luca Ferrari',
               'turni_preferiti': ['N'],
               'turni_indesiderati': ['M'],
               'giorni_indisponibilita': ['2027-01-01'],
               'flexibility_score': 0.4,
               'satisfaction_weights': {'M': -0.7, 'P': 0.0, 'N': 1.0}},
    'W04': {   'nome': 'Sara Russo',
               'turni_preferiti': ['P'],
               'turni_indesiderati': ['N'],
               'giorni_indisponibilita': ['2026-12-31', '2027-01-01'],
               'flexibility_score': 0.1,
               'satisfaction_weights': {'M': 0.0, 'P': 1.0, 'N': -0.9}},
    'W05': {   'nome': 'Andrea Esposito',
               'turni_preferiti': ['P'],
               'turni_indesiderati': [],
               'giorni_indisponibilita': [],
               'flexibility_score': 0.9,
               'satisfaction_weights': {'M': 0.0, 'P': 0.2, 'N': 0.0}},
    'W06': {   'nome': 'Chiara Romano',
               'turni_preferiti': ['M'],
               'turni_indesiderati': ['N'],
               'giorni_indisponibilita': ['2026-12-08'],
               'flexibility_score': 0.3,
               'satisfaction_weights': {'M': 1.0, 'P': 0.0, 'N': -0.7}},
    'W07': {   'nome': 'Matteo Colombo',
               'turni_preferiti': ['N', 'P'],
               'turni_indesiderati': ['M'],
               'giorni_indisponibilita': ['2026-12-19', '2026-12-20'],
               'flexibility_score': 0.5,
               'satisfaction_weights': {'M': -0.6, 'P': 0.8, 'N': 1.0}},
    'W08': {   'nome': 'Francesca Ricci',
               'turni_preferiti': ['M', 'P'],
               'turni_indesiderati': ['N'],
               'giorni_indisponibilita': ['2026-12-26'],
               'flexibility_score': 0.0,
               'satisfaction_weights': {'M': 1.0, 'P': 0.9, 'N': -100.0}},
    'W09': {   'nome': 'Davide Greco',
               'turni_preferiti': ['M', 'N'],
               'turni_indesiderati': ['P'],
               'giorni_indisponibilita': ['2027-01-06'],
               'flexibility_score': 0.7,
               'satisfaction_weights': {'M': 0.5, 'P': -0.4, 'N': 0.5}},
    'W10': {   'nome': 'Elena Marino',
               'turni_preferiti': ['P', 'N'],
               'turni_indesiderati': ['M'],
               'giorni_indisponibilita': ['2026-12-24', '2026-12-25', '2026-12-26'],
               'flexibility_score': 0.3,
               'satisfaction_weights': {'M': -0.6, 'P': 1.0, 'N': 0.7}},
    'W11': {   'nome': 'Alessandro Conti',
               'turni_preferiti': ['M'],
               'turni_indesiderati': ['N'],
               'giorni_indisponibilita': ['2026-12-25'],
               'flexibility_score': 0.4,
               'satisfaction_weights': {'M': 1.0, 'P': 0.0, 'N': -0.6}},
    'W12': {   'nome': 'Valentina Bruno',
               'turni_preferiti': ['N'],
               'turni_indesiderati': [],
               'giorni_indisponibilita': [],
               'flexibility_score': 1.0,
               'satisfaction_weights': {'M': 0.0, 'P': 0.0, 'N': 0.2}},
    'W13': {   'nome': 'Simone Gallo',
               'turni_preferiti': ['P', 'M'],
               'turni_indesiderati': ['N'],
               'giorni_indisponibilita': ['2027-01-01', '2027-01-06'],
               'flexibility_score': 0.2,
               'satisfaction_weights': {'M': 0.8, 'P': 1.0, 'N': -0.7}},
    'W14': {   'nome': 'Roberto Ferrara',
               'turni_preferiti': ['M'],
               'turni_indesiderati': ['N'],
               'giorni_indisponibilita': [],
               'flexibility_score': 0.6,
               'satisfaction_weights': {'M': 1.0, 'P': 0.0, 'N': -0.5}},
    'W15': {   'nome': 'Monica Cattaneo',
               'turni_preferiti': ['P'],
               'turni_indesiderati': ['N'],
               'giorni_indisponibilita': ['2026-12-25', '2026-12-26'],
               'flexibility_score': 0.4,
               'satisfaction_weights': {'M': 0.0, 'P': 1.0, 'N': -0.6}},
    'W16': {   'nome': 'Stefano Leone',
               'turni_preferiti': ['N'],
               'turni_indesiderati': [],
               'giorni_indisponibilita': [],
               'flexibility_score': 0.9,
               'satisfaction_weights': {'M': 0.0, 'P': 0.0, 'N': 0.2}},
    'W17': {   'nome': 'Laura Mancini',
               'turni_preferiti': ['M'],
               'turni_indesiderati': ['N'],
               'giorni_indisponibilita': ['2027-01-01', '2027-01-06'],
               'flexibility_score': 0.3,
               'satisfaction_weights': {'M': 1.0, 'P': 0.0, 'N': -0.7}},
    'W18': {   'nome': 'Gianni Serra',
               'turni_preferiti': ['P'],
               'turni_indesiderati': [],
               'giorni_indisponibilita': [],
               'flexibility_score': 1.0,
               'satisfaction_weights': {'M': 0.0, 'P': 0.2, 'N': 0.0}},
    'W19': {   'nome': 'Paola Costa',
               'turni_preferiti': ['M', 'P'],
               'turni_indesiderati': ['N'],
               'giorni_indisponibilita': ['2026-12-25'],
               'flexibility_score': 0.5,
               'satisfaction_weights': {'M': 0.9, 'P': 0.8, 'N': -0.5}},
    'W20': {   'nome': 'Fabio Martini',
               'turni_preferiti': ['N', 'P'],
               'turni_indesiderati': ['M'],
               'giorni_indisponibilita': [],
               'flexibility_score': 0.4,
               'satisfaction_weights': {'M': -0.6, 'P': 0.8, 'N': 1.0}}}
